apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: home
spec:
  chart:
    spec:
      chart: sonarr
      version: 16.3.x
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: sonarr
  values:
    env:
      TZ: America/Kentucky/Louisville
      PUID: 1000
      PGID: 1000
    controller:
      labels:
        app: sonarr
      replicas: 1
    service:
      labels:
        app: sonarr
    initContainers:
      update-volume-permissions:
        image: busybox:1.35.0
        command: ["/bin/sh", "-c"]
        args: ["chown -R 1000:1000 /config; chown -R 1000:1000 /torrents; chown -R 1000:1000 /usenet"]
        volumeMounts:
          - name: config
            mountPath: /config
          - name: torrents
            mountPath: /torrents
          - name: usenet
            mountPath: /usenet
        securityContext:
          runAsUser: 0
    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      fsGroupChangePolicy: "OnRootMismatch"
    persistence:
        config:
          enabled: true
          type: pvc
          existingClaim: sonarr-config
          mountPath: /config
        downloads-usenet:
          enabled: true
          type: pvc
          existingClaim: downloads-usenet
          mountPath: /usenet
        downloads-torrents:
          enabled: true
          type: pvc
          existingClaim: downloads-torrents
          mountPath: /torrents
        tv:
          enabled: true
          type: custom
          volumeSpec:
            nfs:
              path: /mnt/Main/Media/TV
              server: 10.254.30.11
          mountPath: /tv