apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn
spec:
  targetNamespace: longhorn
  interval: 1m
  chart:
    spec:
      chart: longhorn
      version: '1.3.1'
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: longhorn
      interval: 1m
  # values: 