apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn
spec:
  chart:
    spec:
      chart: longhorn
      version: 1.3.1
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: longhorn
  values:
    persistence:
        defaultClassReplicaCount: 2
        defaultDataLocality: best-effort
    defaultSettings:
        defaultDataLocality: best-effort
        defaultReplicaCount: 2
