apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: media
  namespace: media
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`radarr.media.k3s.bholland.org`) || (Host(`media.k3s.bholland.org`) && PathPrefix(`/radarr/`))
      kind: Rule
      services:
        - kind: Service
          name: radarr
          namespace: media
          port: 7878
    - match: Host(`radarr-4k.media.k3s.bholland.org`) || (Host(`media.k3s.bholland.org`) && PathPrefix(`/radarr-4k/`))
      kind: Rule
      services:
        - kind: Service
          name: radarr-4k
          namespace: media
          port: 7878
    - match: Host(`sonarr.media.k3s.bholland.org`) || (Host(`media.k3s.bholland.org`) && PathPrefix(`/sonarr/`))
      kind: Rule
      services:
        - kind: Service
          name: sonarr
          namespace: media
          port: 8989
    - match: Host(`sonarr-anime.media.k3s.bholland.org`) || (Host(`media.k3s.bholland.org`) && PathPrefix(`/sonarr-anime/`))
      kind: Rule
      services:
        - kind: Service
          name: sonarr-anime
          namespace: media
          port: 8989
    - match: Host(`prowlarr.media.k3s.bholland.org`) || (Host(`media.k3s.bholland.org`) && PathPrefix(`/prowlarr/`))
      kind: Rule
      services:
        - kind: Service
          name: prowlarr
          namespace: media
          port: 9696
    - match: Host(`sabnzbd.media.k3s.bholland.org`) || (Host(`media.k3s.bholland.org`) && PathPrefix(`/sabnzbd/`))
      kind: Rule
      services:
        - kind: Service
          name: sabnzbd
          namespace: media
          port: 8080
    - match: Host(`qbt.media.k3s.bholland.org`) || (Host(`media.k3s.bholland.org`) && PathPrefix(`/qbt/`))
      kind: Rule
      services:
        - kind: Service
          name: qbt
          namespace: media
          port: 8080

  tls:
    secretName: media-k3s-bholland-org-staging-tls
