apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sabnzbd
  namespace: media
spec:
  chart:
    spec:
      chart: sabnzbd
      version: 9.4.x
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: sabnzbd
  values:
    global:
      labels:
        app: sabnzbd
    env:
      TZ: America/Kentucky/Louisville
      PUID: 1000
      PGID: 1000
    initContainers:
      update-volume-permissions:
        image: busybox:1.35.0
        command: ["/bin/sh", "-c"]
        args: ["chown -R 1000:1000 /config; chown -R 1000:1000 /usenet"]
        volumeMounts:
          - name: config
            mountPath: /config
          - name: usenet
            mountPath: /usenet
        securityContext:
          runAsUser: 0
    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      fsGroupChangePolicy: "OnRootMismatch"
    persistence:
        config:
          enabled: true
          type: pvc
          existingClaim: sabnzbd-config
          mountPath: /config
        usenet:
          enabled: true
          type: pvc
          existingClaim: usenet
          mountPath: /usenet
        schtuff:
          enabled: true
          type: custom
          volumeSpec:
            nfs:
              path: /mnt/SASSY/Schtuff
              server: 10.254.30.11
          mountPath: /schtuff