apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: media
spec:
  chart:
    spec:
      chart: qbittorrent
      version: 13.5.x
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: qbittorrent
  values:
    global:
      fullnameOverride: qbt
      labels:
        app: qbt
    image:
      tag: latest
    env:
      TZ: America/Kentucky/Louisville
      PUID: 1000
      PGID: 1000
    initContainers:
      update-volume-permissions:
        image: busybox:1.35.0
        command: ["/bin/sh", "-c"]
        args: ["chown -R 1000:1000 /config;"]
        volumeMounts:
          - name: config
            mountPath: /config
          - name: downloads
            mountPath: /downloads
        securityContext:
          runAsUser: 0
    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      fsGroupChangePolicy: "OnRootMismatch"
    persistence:
        config:
          enabled: true
          type: pvc
          existingClaim: qbt-config
          mountPath: /config
        downloads:
          enabled: true
          type: pvc
          existingClaim: torrents
          mountPath: /downloads
        sassy:
          enabled: true
          type: custom
          volumeSpec:
            nfs:
              path: /mnt/SASSY/Downloads
              server: 10.254.30.11
          mountPath: /sassy